const crypto = require("crypto");
const prisma = require("../../config/prisma");
const { accessTokenCookieOptions } = require("../../config/authCookie");

const SESSION_TOUCH_INTERVAL_MS = 60 * 1000;
const MAX_USER_AGENT_LENGTH = 500;
const MAX_DEVICE_ID_LENGTH = 128;

const getSessionExpiry = () =>
  new Date(Date.now() + accessTokenCookieOptions.maxAge);

const normalizeUserAgent = (userAgent) => {
  const value = String(userAgent || "").trim();
  return value ? value.slice(0, MAX_USER_AGENT_LENGTH) : null;
};

const normalizeDeviceId = (deviceId) => {
  const value = String(deviceId || "").trim();

  if (!value || value.length > MAX_DEVICE_ID_LENGTH) return null;

  // Device IDs are generated by this server. Restrict accepted cookie values
  // to a safe token format before storing them in the database.
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : null;
};

const resolveDeviceId = (deviceId) =>
  normalizeDeviceId(deviceId) || crypto.randomUUID();

const createUserSession = async (userId, metadata = {}) => {
  const now = new Date();
  const deviceId = resolveDeviceId(metadata.deviceId);
  const userAgent = normalizeUserAgent(metadata.userAgent);

  // Link sessions created before device tracking to the stable ID on the next
  // login from that browser. This avoids showing the same browser twice.
  if (userAgent) {
    await prisma.userSession.updateMany({
      where: {
        userId,
        userAgent,
        deviceId: null,
      },
      data: { deviceId },
    });
  }

  // Historical sessions are intentionally retained. The admin dashboard uses
  // their stable device IDs to report how many devices an account has used.
  return prisma.userSession.create({
    data: {
      userId,
      userAgent,
      deviceId,
      lastSeenAt: now,
      expiresAt: getSessionExpiry(),
    },
  });
};

const createAccountSession = async ({
  model,
  accountField,
  accountId,
  metadata = {},
}) => {
  const now = new Date();
  const deviceId = resolveDeviceId(metadata.deviceId);
  const userAgent = normalizeUserAgent(metadata.userAgent);

  return prisma[model].create({
    data: {
      [accountField]: accountId,
      userAgent,
      deviceId,
      lastSeenAt: now,
      expiresAt: getSessionExpiry(),
    },
  });
};

const createStaffSession = (staffAccountId, metadata = {}) =>
  createAccountSession({
    model: "staffSession",
    accountField: "staffAccountId",
    accountId: staffAccountId,
    metadata,
  });

const createGarageOwnerSession = (garageOwnerId, metadata = {}) =>
  createAccountSession({
    model: "garageOwnerSession",
    accountField: "garageOwnerId",
    accountId: garageOwnerId,
    metadata,
  });

const createGarageControllerSession = (garageControllerId, metadata = {}) =>
  createAccountSession({
    model: "garageControllerSession",
    accountField: "garageControllerId",
    accountId: garageControllerId,
    metadata,
  });

const createCustomerSupportSession = (supportAccountId, metadata = {}) =>
  createAccountSession({
    model: "customerSupportSession",
    accountField: "supportAccountId",
    accountId: supportAccountId,
    metadata,
  });

const getActiveUserSession = (sessionId, userId) =>
  prisma.userSession.findFirst({
    where: {
      id: sessionId,
      userId,
      revokedAt: null,
      expiresAt: { gt: new Date() },
    },
    select: {
      id: true,
      lastSeenAt: true,
      expiresAt: true,
    },
  });

const getActiveAccountSession = (model, accountField, sessionId, accountId) =>
  prisma[model].findFirst({
    where: {
      id: sessionId,
      [accountField]: accountId,
      revokedAt: null,
      expiresAt: { gt: new Date() },
    },
    select: {
      id: true,
      lastSeenAt: true,
      expiresAt: true,
    },
  });

const getActiveStaffSession = (sessionId, staffAccountId) =>
  getActiveAccountSession(
    "staffSession",
    "staffAccountId",
    sessionId,
    staffAccountId,
  );

const getActiveGarageOwnerSession = (sessionId, garageOwnerId) =>
  getActiveAccountSession(
    "garageOwnerSession",
    "garageOwnerId",
    sessionId,
    garageOwnerId,
  );

const getActiveGarageControllerSession = (sessionId, garageControllerId) =>
  getActiveAccountSession(
    "garageControllerSession",
    "garageControllerId",
    sessionId,
    garageControllerId,
  );

const getActiveCustomerSupportSession = (sessionId, supportAccountId) =>
  getActiveAccountSession(
    "customerSupportSession",
    "supportAccountId",
    sessionId,
    supportAccountId,
  );

const touchUserSession = async (sessionId, userId) => {
  const now = new Date();
  const cutoff = new Date(now.getTime() - SESSION_TOUCH_INTERVAL_MS);

  await prisma.userSession.updateMany({
    where: {
      id: sessionId,
      userId,
      revokedAt: null,
      expiresAt: { gt: now },
      lastSeenAt: { lte: cutoff },
    },
    data: { lastSeenAt: now },
  });
};

const touchAccountSession = async (model, accountField, sessionId, accountId) => {
  const now = new Date();
  const cutoff = new Date(now.getTime() - SESSION_TOUCH_INTERVAL_MS);

  await prisma[model].updateMany({
    where: {
      id: sessionId,
      [accountField]: accountId,
      revokedAt: null,
      expiresAt: { gt: now },
      lastSeenAt: { lte: cutoff },
    },
    data: { lastSeenAt: now },
  });
};

const touchStaffSession = (sessionId, staffAccountId) =>
  touchAccountSession(
    "staffSession",
    "staffAccountId",
    sessionId,
    staffAccountId,
  );

const touchGarageOwnerSession = (sessionId, garageOwnerId) =>
  touchAccountSession(
    "garageOwnerSession",
    "garageOwnerId",
    sessionId,
    garageOwnerId,
  );

const touchGarageControllerSession = (sessionId, garageControllerId) =>
  touchAccountSession(
    "garageControllerSession",
    "garageControllerId",
    sessionId,
    garageControllerId,
  );

const touchCustomerSupportSession = (sessionId, supportAccountId) =>
  touchAccountSession(
    "customerSupportSession",
    "supportAccountId",
    sessionId,
    supportAccountId,
  );

const revokeUserSession = async (sessionId, userId) => {
  if (!sessionId || !userId) return;

  await prisma.userSession.updateMany({
    where: {
      id: sessionId,
      userId,
      revokedAt: null,
    },
    data: {
      revokedAt: new Date(),
    },
  });
};

const revokeAccountSession = async (model, accountField, sessionId, accountId) => {
  if (!sessionId || !accountId) return;

  await prisma[model].updateMany({
    where: {
      id: sessionId,
      [accountField]: accountId,
      revokedAt: null,
    },
    data: {
      revokedAt: new Date(),
    },
  });
};

const revokeStaffSession = (sessionId, staffAccountId) =>
  revokeAccountSession(
    "staffSession",
    "staffAccountId",
    sessionId,
    staffAccountId,
  );

const revokeGarageOwnerSession = (sessionId, garageOwnerId) =>
  revokeAccountSession(
    "garageOwnerSession",
    "garageOwnerId",
    sessionId,
    garageOwnerId,
  );

const revokeGarageControllerSession = (sessionId, garageControllerId) =>
  revokeAccountSession(
    "garageControllerSession",
    "garageControllerId",
    sessionId,
    garageControllerId,
  );

const revokeCustomerSupportSession = (sessionId, supportAccountId) =>
  revokeAccountSession(
    "customerSupportSession",
    "supportAccountId",
    sessionId,
    supportAccountId,
  );

const revokeAllUserSessions = async (userId) => {
  if (!userId) return;

  await prisma.userSession.updateMany({
    where: {
      userId,
      revokedAt: null,
    },
    data: {
      revokedAt: new Date(),
    },
  });
};

const revokeAllStaffSessions = async (staffAccountId) => {
  if (!staffAccountId) return;

  await prisma.staffSession.updateMany({
    where: {
      staffAccountId,
      revokedAt: null,
    },
    data: {
      revokedAt: new Date(),
    },
  });
};

const revokeAllCustomerSupportSessions = async (supportAccountId) => {
  if (!supportAccountId) return;

  await prisma.customerSupportSession.updateMany({
    where: {
      supportAccountId,
      revokedAt: null,
    },
    data: {
      revokedAt: new Date(),
    },
  });
};

module.exports = {
  createGarageControllerSession,
  createCustomerSupportSession,
  createGarageOwnerSession,
  createStaffSession,
  createUserSession,
  getActiveCustomerSupportSession,
  getActiveGarageControllerSession,
  getActiveGarageOwnerSession,
  getActiveStaffSession,
  getActiveUserSession,
  revokeAllCustomerSupportSessions,
  revokeAllStaffSessions,
  revokeAllUserSessions,
  revokeCustomerSupportSession,
  revokeGarageControllerSession,
  revokeGarageOwnerSession,
  revokeStaffSession,
  revokeUserSession,
  touchCustomerSupportSession,
  touchGarageControllerSession,
  touchGarageOwnerSession,
  touchStaffSession,
  touchUserSession,
};
