const Section = ({ title, children }) => <section><h2 className="text-xl font-bold text-ink">{title}</h2><div className="mt-3 leading-7 text-ink">{children}</div></section>;
const items = {
  information: ["Name, phone number, email address.", "Vehicle details and service history.", "Pickup and delivery address.", "Location data during booking and live tracking.", "Payment information processed through secure payment partners.", "Photos uploaded during pickup and delivery."],
  use: ["To process bookings and provide pickup & drop services.", "To connect customers with verified garages.", "To improve service quality and customer support.", "To send booking updates and promotional communications."],
};

export default function PrivacyPolicy() {
  return <div className="container-x py-10 sm:py-16"><article className="mx-auto max-w-3xl rounded-2xl border border-line bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-dark">Legal</p><h1 className="mt-2 text-3xl font-bold text-ink">Rovauto Privacy Policy</h1><p className="mt-2 text-sm text-muted">Effective Date: —</p><p className="mt-6 leading-7 text-ink">Rovauto (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) values your privacy. This Privacy Policy explains how we collect, use, store and protect your information when you use Rovauto&apos;s website, mobile application and services.</p><div className="mt-8 space-y-8"><Section title="Information We Collect"><ul className="list-disc space-y-2 pl-5">{items.information.map((item) => <li key={item}>{item}</li>)}</ul></Section><Section title="How We Use Information"><ul className="list-disc space-y-2 pl-5">{items.use.map((item) => <li key={item}>{item}</li>)}</ul></Section><Section title="Data Sharing"><p>We may share necessary information only with verified garage partners, logistics partners, payment providers and where required by law.</p></Section><Section title="Data Security"><p>We use reasonable administrative and technical safeguards. No online system is completely secure.</p></Section><Section title="Your Rights"><p>You may request correction or deletion of your personal information subject to legal obligations.</p></Section><Section title="Cookies"><p>Our platform may use cookies and analytics tools to improve user experience.</p></Section><Section title="Policy Updates"><p>We may update this Privacy Policy from time to time. Continued use of Rovauto constitutes acceptance of the updated policy.</p></Section></div><div className="mt-8 border-t border-line pt-6 text-sm text-muted"><p className="font-semibold text-ink">Contact</p><a className="mt-2 block underline" href="mailto:support@rovauto.com">support@rovauto.com</a><a className="mt-1 block underline" href="https://rovauto.com">https://rovauto.com</a></div></article></div>;
}
