const express = require("express");
const controller = require("../../garage/controllers/controller.controller");
const { protect } = require("../../middlewares/auth.middleware");
const { authorizeRoles } = require("../../middlewares/role.middleware");
const validate = require("../../middlewares/validate.middleware");
const rules = require("../../garage/validations/controller.validation");

const router = express.Router();
router.use(protect);
router.use(authorizeRoles("ADMIN"));
router.get("/", rules.optionalGarageId, validate, controller.list);
router.post("/garage/:garageId", rules.adminCreate, validate, controller.create);
router.get("/:controllerId/activity", rules.controllerId, validate, controller.activity);
router.patch("/:controllerId", rules.update, validate, controller.update);
router.patch("/:controllerId/password", rules.password, validate, controller.resetPassword);
router.post("/:controllerId/revoke-sessions", rules.controllerId, validate, controller.revokeSessions);
router.delete("/:controllerId", rules.controllerId, validate, controller.remove);
router.patch("/garage/:garageId/limit", rules.limit, validate, controller.setLimit);
router.post("/bookings/:bookingId/transfer", rules.transfer, validate, controller.transfer);
module.exports = router;
