import { useEffect, useMemo, useState } from "react";
import { adminApi } from "@/api/admin";
import { FiAlertCircle, FiCheckCircle, FiEdit2, FiKey, FiPlus, FiRefreshCw, FiShield, FiUserCheck, FiUserX, FiX } from "react-icons/fi";

const EMPTY = { name: "", email: "", password: "" };
const formatDate = (value) => value ? new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "Never";
const getError = (error, fallback) => error.response?.data?.message || error.message || fallback;

export default function SubAdminAccounts() {
  const [accounts, setAccounts] = useState([]); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [passwordAccount, setPasswordAccount] = useState(null); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const summary = useMemo(() => ({ total: accounts.length, active: accounts.filter(a=>a.isActive).length }), [accounts]);
  const load = async () => { setLoading(true); setError(""); try { const data = await adminApi.getSubAdminAccounts(); setAccounts(Array.isArray(data)?data:[]); } catch(e){setError(getError(e,"Unable to load sub-admin accounts"));} finally{setLoading(false);} };
  useEffect(()=>{void load();},[]);
  const create = async(e)=>{e.preventDefault();setSaving(true);setError("");try{await adminApi.createSubAdminAccount({name:form.name.trim(),email:form.email.trim().toLowerCase(),password:form.password});setForm(EMPTY);setSuccess("Sub-admin created. They can log in with email, password and OTP.");await load();}catch(err){setError(getError(err,"Unable to create sub-admin"));}finally{setSaving(false);}};
  const saveEdit=async()=>{setSaving(true);setError("");try{await adminApi.updateSubAdminAccount(editing.id,{name:editing.name.trim(),email:editing.email.trim().toLowerCase(),isActive:Boolean(editing.isActive)});setEditing(null);setSuccess("Sub-admin updated.");await load();}catch(err){setError(getError(err,"Unable to update sub-admin"));}finally{setSaving(false);}};
  const changePassword=async(e)=>{e.preventDefault();setSaving(true);setError("");try{await adminApi.changeSubAdminPassword(passwordAccount.id,password);setPasswordAccount(null);setPassword("");setSuccess("Password changed and all existing sessions revoked.");await load();}catch(err){setError(getError(err,"Unable to change password"));}finally{setSaving(false);}};
  return <div className="space-y-6"><section className="rounded-2xl border border-line bg-white p-5 shadow-soft"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-muted">Main-admin only</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-extrabold text-ink"><FiShield/>Sub-admin accounts</h1><p className="mt-2 max-w-3xl text-sm text-muted">Sub-admins have operational admin access. Dangerous commands, destructive bulk actions, wallet transfers and staff-account management remain unavailable.</p></div><button onClick={load} className="flex h-10 items-center gap-2 rounded-lg border border-line px-3 text-sm font-bold"><FiRefreshCw className={loading?"animate-spin":""}/>Refresh</button></div></section>
  {error&&<div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><FiAlertCircle/>{error}</div>}{success&&<div className="flex gap-2 rounded-xl border border-green-200 bg-green-50 p-4 text-sm text-green-700"><FiCheckCircle/>{success}</div>}
  <section className="grid gap-4 sm:grid-cols-3">{[["Total",summary.total,FiShield],["Active",summary.active,FiUserCheck],["Disabled",summary.total-summary.active,FiUserX]].map(([label,value,Icon])=><article key={label} className="rounded-2xl border border-line bg-white p-5"><Icon/><p className="mt-3 text-xs font-bold uppercase text-muted">{label}</p><p className="text-3xl font-extrabold text-ink">{value}</p></article>)}</section>
  <form onSubmit={create} className="grid gap-3 rounded-2xl border border-line bg-white p-5 md:grid-cols-4"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name" className="h-11 rounded-lg border border-line px-3"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email" className="h-11 rounded-lg border border-line px-3"/><input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Strong password" className="h-11 rounded-lg border border-line px-3"/><button disabled={saving} className="flex h-11 items-center justify-center gap-2 rounded-lg bg-ink font-bold text-white"><FiPlus/>Create sub-admin</button></form>
  <section className="overflow-hidden rounded-2xl border border-line bg-white"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-bg-soft text-xs uppercase text-muted"><tr><th className="px-5 py-3">Account</th><th className="px-5 py-3">Created by</th><th className="px-5 py-3">Last login</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-line">{accounts.map(a=><tr key={a.id}><td className="px-5 py-4"><p className="font-bold">{a.name}</p><p className="text-xs text-muted">{a.email}</p></td><td className="px-5 py-4 text-xs text-muted">{a.createdByName||"Main admin"}</td><td className="px-5 py-4 text-xs text-muted">{formatDate(a.lastLoginAt)}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${a.isActive?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{a.isActive?"Active":"Disabled"}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={()=>setEditing({...a})} className="grid h-9 w-9 place-items-center rounded-lg border border-line"><FiEdit2/></button><button onClick={()=>setPasswordAccount(a)} className="grid h-9 w-9 place-items-center rounded-lg border border-line"><FiKey/></button></div></td></tr>)}{!loading&&!accounts.length&&<tr><td colSpan="5" className="p-10 text-center text-muted">No sub-admin accounts yet.</td></tr>}</tbody></table></div></section>
  {editing&&<div className="fixed inset-0 z-[130] grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">Edit sub-admin</h2><button onClick={()=>setEditing(null)}><FiX/></button></div><div className="mt-4 grid gap-3"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} className="h-11 rounded-lg border border-line px-3"/><input type="email" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})} className="h-11 rounded-lg border border-line px-3"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/>Active account</label><button onClick={saveEdit} className="h-11 rounded-lg bg-ink font-bold text-white">Save</button></div></div></div>}
  {passwordAccount&&<div className="fixed inset-0 z-[130] grid place-items-center bg-black/60 p-4"><form onSubmit={changePassword} className="w-full max-w-md rounded-2xl bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">Change password</h2><button type="button" onClick={()=>setPasswordAccount(null)}><FiX/></button></div><p className="mt-2 text-sm text-muted">{passwordAccount.name}</p><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="New strong password" className="mt-4 h-11 w-full rounded-lg border border-line px-3"/><button className="mt-3 h-11 w-full rounded-lg bg-ink font-bold text-white">Change and revoke sessions</button></form></div>}</div>;
}
